/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 only-keyboard.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/only-keyboard-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Keyboard.geometry} material={materials.Keyboard_Material} position={[2.28, -1.99, 2.66]} scale={0.03} />
      <mesh geometry={nodes.GlassBackground.geometry} material={materials.Glass_Material} position={[0.01, -2.42, 1.37]} scale={0.06} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Plane_Material} position={[0.01, -3.18, 1.37]} scale={0.06} />
      <mesh geometry={nodes.Paper.geometry} material={materials.Paper_material} position={[0.09, -0.62, 3.6]} scale={3.44} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Cube_Material} position={[0, -4, 1.59]} scale={5.04} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.005']} position={[-0.8, -2.09, 1.02]} scale={0.4} />
    </group>
  )
}

useGLTF.preload('/only-keyboard-transformed.glb')
