/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 keyboard.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'  // Import the useFrame hook

export default function Keyboard(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/only-keyboard-transformed.glb')
  useFrame(() => {
    group.current.rotation.x += 0.004;
  })
  return (
    <group  {...props} dispose={null} rotation={[Math.PI/1.5,0,0]} position={[1.2,0,0]}>
      <mesh ref={group} geometry={nodes.Keyboard.geometry} rotation={[0,0,0]} material={materials.Paper_material} position={[2.2, -2, -1]} scale={0.04} />
      {/* <mesh geometry={nodes.GlassBackground.geometry} material={materials.Glass_Material} position={[0.01, -2.42, 1.37]} scale={0.08} /> */}
      {/* <mesh geometry={nodes.Paper.geometry} material={materials.Paper_material} position={[0.09, -0.62, 3.6]} scale={3.44} /> */}
      {/* <mesh geometry={nodes.Cube.geometry} material={materials.Cube_Material} position={[0, -4, 1.59]} scale={5.04} />   */}
      {/* <mesh geometry={nodes.Text.geometry} material={materials['Material.005']} position={[-0.8, -2.09, 1.02]} scale={0.8} /> */}
    </group>
  )
}

useGLTF.preload('/only-keyboard-transformed.glb')
